name: flutter_multi_carousel
description: A simple Carousel Package with multiple types and configurations.
version: 1.0.3
author: Shubham Jaiswal <jaiswal.shubham84@gmail.com>
homepage: https://github.com/GeekyAnts/flutter-carousel

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
